### ISSUE TITLE
Creating triggers in multi instance spring boot project leads to ObjectAlreadyExists exception

### ISSUE THREAD

**Issue by RajNirmal** [quartz-scheduler/quartz#795]
I have a clustered spring boot project in which the required trigger timings are defined in the appliction.yml. When the application starts up I have `@configuration` file in the `PostConstruct` of which I am reading the yml and forming the job, trigger and calling `scheduleJob` on it. I have configured JDBC datastore with the following settings

```
jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            dataSource: quartzDataSource
            tablePrefix: qrtz_
            txIsolationLevelSerializable: true

```

When I try to start up 3 containers of this project the `configuration` file of all 3 containers run at the same time and try to create trigger which is leading to a `ObjectAlreadyExists` exception to be thrown. Since all the containers are starting up at the same time if I try to perform an `scheduler.checkExists` check before creating the application is saying no trigger exists.

Similarly I also tried scheduling the job using the replace functionality `scheduler.scheduleJob(job, mutableSetOf(trigger), true)`. The same issue that is mentioned above is also happening in this scenario. In the `JobStoreSupport` class it is checked if the trigger is already existing and an exception is thrown immediately. Since all the containers reach that line of execution at the same time the exception is not thrown. When trying to `insert` the trigger a `Primary key unique constraint` is violated as a different container has already inserted that particular job with the corresponding trigger.

How can I configure quartz such a way that these exceptions do not occur when the service is starting up?
