### ISSUE TITLE
Trigger table is always empty

### ISSUE THREAD

**Issue by hasanli-orkhan** [quartz-scheduler/quartz#818]
Hello.
I use spring boot + postgres + quartz.
Here is my config file (application.yml)
```yml
spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      schema: classpath:db/quartz_tables.sql
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            skipUpdateCheck: true
          dataSource:
            quartzDataSource:
              driver: org.postgresql.Driver
              URL: jdbc:postgresql://localhost:5432/test
              user: postgres
              password: postgres
              maxConnections: 30
              provider: hikaricp
          jobStore:
            isClustered: false
            useProperties: false
#            class: org.springframework.scheduling.quartz.JobStoreCMT
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
#            class: org.springframework.scheduling.quartz.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: quartzDataSource
            tablePrefix: qrtz_
            misfireThreshold: 60000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 30
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
```

When I using StdJDBCDelegate the triggers table is filled, but I'm getting the exception:
`Couldn't acquire next trigger: Couldn't retrieve trigger: Bad value for type long : \x`
When I using PostgreSQLDelegate the triggers table is empty and I can't get the TriggerState.
How I can fix this?
Also created the question on SO:
https://stackoverflow.com/questions/72760428/why-did-quartz-jobs-triggerstate-is-none-instead-if-complete
Thanks in advance!
